# Generated by Django 4.2.3 on 2023-07-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="technology",
            field=models.CharField(max_length=50),
        ),
    ]
