# Generated by Django 4.2.3 on 2023-08-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_project_technology"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="link",
            field=models.CharField(default="", max_length=50),
        ),
    ]
