# Generated by Django 4.2.3 on 2023-07-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_me", "0004_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(upload_to="about_me/img"),
        ),
    ]
